mysql:
  host: 127.0.0.1
  port: 3306
  db-name: gin_study
  username: root
  password: 12345
  log_level: dev
logger:
  level: info
  prefix: '[gin_study]'
  director: log
  show-line: true
  log-in-console: true
system:
  host: "0.0.0.0"
  port: 8080
  env: dev
